services:
  s3:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z-cpuv1
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
      MINIO_DOMAIN: s3.us-east-1.amazonaws.com
    restart: always
    networks:
      default:
        aliases:
          - voice-recorder-2025.s3.us-east-1.amazonaws.com

volumes:
    data:
